### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by andrewdalpino** [UditAgarwal27/SentimentChecker#1]
Hello, thanks for using Rubix and forking our Sentiment example project! Can you please include the original license and copyright notice with this repository as stipulated by the MIT license?

https://github.com/RubixML/Sentiment

https://github.com/RubixML/Sentiment/blob/master/LICENSE.md

Thank you!

Andrew

P.S. Please include a citation and any accompanying copyright notices that were originally posted with the original dataset as well if you are going to offer it for download via Google Drive.

**Comment by UditAgarwal27** [comment]
Sure. Will do that

**Comment by UditAgarwal27** [comment]
Hello, i am still a beginner in all this. Can you guide me with the process. That would be much helpful. Thank you.

**Comment by andrewdalpino** [comment]
Hey @UditAgarwal27 no worries, the easiest way to fork a repo such that it contains all the original licenses, copyright notices, citations, etc. is to use the GitHub fork button

<img width="86" alt="Screenshot 2020-10-29 021509" src="https://user-images.githubusercontent.com/18690561/97537308-9a504600-198c-11eb-8002-a0850ced7790.png">

Otherwise you could just push the all the required files like you did with all the other files

**Comment by UditAgarwal27** [comment]
Hi again, i have added LICENSE.md and data_description.txt . What about that copyright notice?

**Comment by andrewdalpino** [comment]
That's perfect thank you @UditAgarwal27 I appreciate it! The LICENCE file contains the copyright notice

Join us in our Telegram channel if you want https://t.me/RubixML

Let me know if you have any questions about the library :)
